name: build & test

on:
  pull_request:
    paths-ignore:
      - "*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Run test on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Test installing gh cli
        run: node .
        env:
          version: 2.28.0

      - name: Test gh command works
        run: gh --version
